README.md

**The following implementations are as follows:**
* added fiel structure to main

ADD: Initial File Structure

---

src/styles/home.css

Fixed navbar bug hwen the page is scrolled and also button effects bug where when clicked, the button texts are gone.

Fixed navbar and button effect bugs

---

src/pages/settings.html
src/styles/settings.css

Merging updated settings.html

---

src/pages/login/signup/index.css
src/pages/login/signup/index.html
src/pages/login/signup/login.css
src/pages/login/signup/login.html
src/pages/login/signup/login.js

Made a modal for login in index.html page when not logged in and modified some css files

login modal and  index(not logged in) modifications

---

src/components/header.html
src/pages/home.html
src/pages/settings.html
src/styles/header.css
src/styles/home.css
src/styles/settings.css

Added reusable header.html for consistency, updated home and settings pages to use it, and added a header.css for styling.

Changes: Resolved a header issue

---

src/index.html
src/pages/home.html
src/pages/settings.html

Few changes to the button path
still some bug fixes to be done

Fullstack PR to development

---

index.html

so that github pages can detect it

MODIFIED: index.html file path moved to root/ directly

---

index.html
src/components/header.html
src/pages/home.html
src/pages/settings.html
src/styles/header.css

Changes:
- Updated the header so that clicking the logo redirects to the home page.  
- Resized the navbar height for better appearance.

Modified Header

---

src/components/notification.html
src/pages/home.html
src/pages/settings.html
src/scripts/notification.js
src/styles/notification.css

Added a Notifications button that opens a panel with "All" and "Unread" tabs.

Notification component

---

Frontend/components/createpost/CreatePost.css
Frontend/components/createpost/CreatePost.jsx
Frontend/components/header/Header.jsx
Frontend/components/loginRegister/LoginRegister.css
Frontend/components/loginRegister/LoginRegister.jsx
Frontend/package-lock.json
Frontend/package.json

added CreatePost, LoginRegister components, and installed axios

added CreatePost, LoginRegister components, and installed axios

---

Frontend/src/App.jsx
Frontend/src/components/header/Header.css
Frontend/src/components/header/Header.jsx
Frontend/src/components/loginRegister/LoginRegister.jsx
Frontend/src/pages/about/About.jsx
Frontend/src/pages/feedpage/FeedPage.css
Frontend/src/pages/feedpage/FeedPage.jsx
Frontend/src/pages/feedpage/FeedPost.css
Frontend/src/pages/feedpage/FeedPost.jsx
Frontend/src/pages/profile/Profile.css
Frontend/src/pages/profile/Profile.jsx

I made changes especially on app, header, loginregister, profile
we can now successfully register and login to our website and can now go to profile

I made changes especially on app, header, loginregister, profile

---

Frontend/src/App.jsx
Frontend/src/components/header/Header.jsx
Frontend/src/components/loginRegister/LoginRegister.css
Frontend/src/components/privateRoute/PrivateRoute.jsx
Frontend/src/pages/notFound/NotFound.css
Frontend/src/pages/notFound/NotFound.jsx

The following are as implemented:
* just refer to the commits LOL :D

Pull request from fullstack to reactjs branch

---

.env
Backend/package-lock.json
Backend/package.json
Backend/server.js
Frontend/public/pages/index.html

Merge backend latest to react development

testing notifs branch merge

---

Backend/routes/user/logon.js
Frontend/src/App.jsx
Frontend/src/components/Header.jsx
Frontend/src/components/LoginRegister.jsx
Frontend/src/components/styles/header.css
Frontend/src/pages/Profile.jsx
Frontend/src/pages/styles/profile.css

we can now register again, profile design updated, header profile picture is now sync with profile page picture, header profile dropdown have now smooth animations.

register, profile, profile css, header changes

---

Frontend/src/pages/About.jsx

Edit about message

---

Frontend/package-lock.json
Frontend/package.json
Frontend/src/App.jsx
Frontend/src/pages/HelpSupport.jsx
Frontend/src/pages/styles/HelpSupport.css

created Help and Support page and designed it already.
downloaded some MUI for icons

Created Help and Support page

---

Frontend/package-lock.json
Frontend/package.json
Frontend/src/components/FeedPost.jsx
Frontend/src/components/styles/feedpost.css
Frontend/src/components/styles/feedpostskeleton.css
Frontend/src/components/utils/formatDate.js
Frontend/src/pages/FeedPage.jsx
Frontend/src/pages/styles/feedpage.css
Frontend/src/store/feedStore.js

Improvements to feedpage and feedposts
improve presentation to user

Fullstack pull request to reactjs

---

Frontend/src/components/CreatePost.jsx

The following fixes are:
* Create Post logic, fixed the caption not being pushed to backend

Patch Version 1.1.2

---

Frontend/src/components/CreateRecipe.jsx

the create recipe now accepts category inputs it is now stored on the same column in the database as the title

the create recipe now accepts category inputs

---

Frontend/src/components/FeedPost.jsx
Frontend/src/pages/FeedPage.jsx

Immediate patch for utils helper functions

Patch Release Version 1.1.8

---

Frontend/src/components/CreatePost.jsx
Frontend/src/components/styles/createpost.css

ADD: CSS for Create Post

---

Frontend/package.json
Frontend/src/App.jsx
Frontend/src/components/Header.jsx
Frontend/src/components/LoginRegister.jsx

partially solve the updating of the header profile picture.  
what I did is instead of going into the feeds immediately after logging in or registering in. The user will be redireted to the user's profile page so that the picture in header will be updated immediately and the user wil have a chance to customize its profile

header profile picture issue

---

Frontend/src/App.jsx
Frontend/src/components/FeedPost.jsx
Frontend/src/components/Header.jsx
Frontend/src/components/styles/feedpost.css
Frontend/src/pages/OtherUserProfile.jsx
Frontend/src/pages/styles/OtherUserProfile.css

added help and support on header even when not logged in, the user can now click on the profile icon on other users and they will be redirected to their profile pages.
implemented follow system but now final yet

help & support, clickable profile icon on posts

---

Frontend/src/components/RecipePage/RecipePost.jsx
Frontend/src/components/RecipePage/styles/recipepost.css
Frontend/src/pages/RecipePage.jsx
Frontend/src/utils/recipeStateStore.js

working Recipe Page

---

Frontend/src/components/LoginRegister.jsx
Frontend/src/components/styles/loginregister.css

adjusting the JSX and CSS in order to fix the bug pop up when you click the login/register button

ADD: Fixing the bug in Login Registration form modal

---

Frontend/src/pages/Settings.jsx
Frontend/src/pages/styles/profile.css
Frontend/src/pages/styles/settings.css
package-lock.json

I created a settings page using React, and styled it. I also slightly modified the background photo on the profile page.

Add: Settings Page React and its Style.

---

Frontend/src/components/FeedPost.jsx
Frontend/src/components/FeedPost/EngagementControls.jsx
Frontend/src/pages/FeedPage.jsx
Frontend/src/pages/OtherUserProfile.jsx
Frontend/src/pages/Profile.jsx

fix my codes after the conflicts resolve is done earlier in profile, otheruserprofile, follower count, followbtn and login modal appearance

fix my codes after the conflicts resolve is done earlier

---

Frontend/src/components/FeedPost/CommentItem.jsx
Frontend/src/components/FeedPost/FeedPostDropdown.jsx
Frontend/src/components/FeedPost/PostComment.jsx
Frontend/src/components/FeedPost/styles/CommentItem.css
Frontend/src/components/FeedPost/styles/EditPost.css
Frontend/src/components/FeedPost/styles/PostComment.css
Frontend/src/pages/FeedPage.jsx

CRUD Implementation to Individual Comment Items

CRUD Implementation to Individual Comment Items

---

Frontend/src/pages/FeedPage.jsx

FIX Web not showing

---

Frontend/src/components/styles/loginregister.css

login register css partial fix

login register css partial fix

---

Frontend/src/components/styles/header.css

FIX header z-index

---

Frontend/src/components/LoginRegister.jsx
Frontend/src/components/styles/header.css

Patch Release Version 1.4.2

---

Frontend/src/components/FeedPost/EngagementControls.jsx

Patch Version 1.4.3

---

Frontend/src/components/CreatePost.jsx
Frontend/src/components/LoginRegister.jsx
Frontend/src/components/styles/createpost.css
Frontend/src/components/styles/createrecipe.css
Frontend/src/components/styles/loginregister.css

Web Responsiveness for LoginRegister and CreatePost

Web Responsiveness for LoginRegister and CreatePost

---

Frontend/src/App.jsx
Frontend/src/components/Header.jsx
Frontend/src/components/Notification.jsx
Frontend/src/components/Notification/NotificationItem.jsx

This Version is for Public Viewing during CPE Fair 2025

RELEASE PUBLIC VERSION v1.4.5b
